### ISSUE TITLE
original data question

### ISSUE THREAD

**Issue by HavenKey** [SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow#3]
Hello! May I ask a question about original data? Why the original data is divided into two files(.edf and .edf.event)?WhenI load it into Matlab,the types were wrong. why?

**Comment by SuperBruceJia** [comment]
Hi,

Sorry for the delayed response! The original data was divided into two parts: .edf data (the EEG time series sequences) and .edf.event (the Event record). So, in this work, we mainly used .edf data instead of .edf.event because we want to use the EEG sequence data. You can use python to load the data and save it into MATLAB files, and use MATLAB to process them.

If you have additional questions, please let me know.

Have a nice day!

Shuyue

**Comment by KisInfinite** [comment]
Hi,&nbsp;
I ran your code yesterday,but the labels was wrong!&nbsp; Please check my annex.
Besides, how can I use python to load the data and save it into MATLAB files?&nbsp;
May I get your wechat number? I have some questions to ask you.


thanks！


Wenqie Huang




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月15日(星期六) 上午10:45
收件人:&nbsp;"SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow"<EEG-Motor-Imagery-Classification-CNNs-TensorFlow@noreply.github.com&gt;;
抄送:&nbsp;"黄文锲"<243986351@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow] original data question (#3)





 
Hi,
 
Sorry for the delayed response! The original data was divided into two parts: .edf data (the EEG time series sequences) and .edf.event (the Event record). So, in this work, we mainly used .edf data instead of .edf.event because we want to use the EEG sequence data. You can use python to load the data and save it into MATLAB files, and use MATLAB to process them.
 
If you have additional questions, please let me know.
 
Have a nice day!
 
Shuyue

**Comment by KisInfinite** [comment]
Hi,
I'm sorry that I made a mistake!
This my annex!
Please check!


Thanks!


Wenqie Huang




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月15日(星期六) 上午10:45
收件人:&nbsp;"SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow"<EEG-Motor-Imagery-Classification-CNNs-TensorFlow@noreply.github.com&gt;;
抄送:&nbsp;"黄文锲"<243986351@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow] original data question (#3)





 
Hi,
 
Sorry for the delayed response! The original data was divided into two parts: .edf data (the EEG time series sequences) and .edf.event (the Event record). So, in this work, we mainly used .edf data instead of .edf.event because we want to use the EEG sequence data. You can use python to load the data and save it into MATLAB files, and use MATLAB to process them.
 
If you have additional questions, please let me know.
 
Have a nice day!
 
Shuyue

**Comment by SuperBruceJia** [comment]
> Hi,&nbsp; I ran your code yesterday,but the labels was wrong!&nbsp; Please check my annex. Besides, how can I use python to load the data and save it into MATLAB files?&nbsp; May I get your wechat number? I have some questions to ask you. thanks！ Wenqie Huang
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月15日(星期六) 上午10:45 收件人:&nbsp;"SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow"<EEG-Motor-Imagery-Classification-CNNs-TensorFlow@noreply.github.com&gt;; 抄送:&nbsp;"黄文锲"<243986351@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow] original data question (#3) Hi, Sorry for the delayed response! The original data was divided into two parts: .edf data (the EEG time series sequences) and .edf.event (the Event record). So, in this work, we mainly used .edf data instead of .edf.event because we want to use the EEG sequence data. You can use python to load the data and save it into MATLAB files, and use MATLAB to process them. If you have additional questions, please let me know. Have a nice day! Shuyue — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Please refer to the "Installation and Usage" Section (https://github.com/SuperBruceJia/EEG-Motor-Imagery-Classification-CNNs-TensorFlow#installation-and-usage) in the README.md. I have clearly pointed that the "Read_Raw_Data_Save_Into_Matlab_Files.py" File MUST be executed under the Python 2 environment, or the labels will be totally messed. My WeChat / WhatsApp / Telegram: +12132965422.

Have a nice day!
